name: CI Workflow with GitHub Secrets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r lab4/requirements.txt 

    - name: Run the app with API key from secrets
      run: |
        echo "Running application with API key"
        python lab4/app.py --api-key ${{ secrets.MY_SECRET_KEY }}  
